### ISSUE TITLE
please refresh labels translations

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#102]
please refresh labels translations I had done some translations

**Comment by gnat42** [comment]
Hello Claudia,
   All refreshed, you'll also notice at the bottom of the page where you do the translations there's a button which says 'Clear Cache'. Translate everything you need to and then click it once. It will clear the cache to make them instantly visible, and will email me the updated translations. So you only need to click it once in total after you're done updating translations, you **don't** need to click it each time or each page.
