### ISSUE TITLE
Issue in editing Lab for Elisa Test done in Site hospital 

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#107]
Most hospital laboratories do not perform ELISA test , however when correcting. If you change the value for " NO"  , the values for the child variables are still saved in the record.
Users are asked to modify these values and put the in the LN tab

![image](https://user-images.githubusercontent.com/23636063/59115400-39e3e300-8917-11e9-9d09-2d6215294d8f.png)

**Comment by gnat42** [comment]
Unfortunately, they need to clear out the related child fields need to be cleared manually or ignored when analyzing data. If we cleared it people could accidentally change something to no, and all fields lose their data, they switch it back to yes and its all gone.
