### ISSUE TITLE
Rotavirus flag issue NL tab 

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#109]
The case is not sent to 
Issue for Flag,  It was not send to RRL but flag is indicating stool send and specimen collection date
Example cases of rota BOL-2-18R-181466

****
![image](https://user-images.githubusercontent.com/23636063/59469608-53979580-8e03-11e9-83a9-4aefa20f6311.png)

**Comment by gnat42** [comment]
still asking for specimenCollectionDate
