### ISSUE TITLE
changes in translation confusion or issue

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#110]
I am a little confused because I thought I did some changes in the translations about a week ago but don see the changes however I know you did some changes to this feature.
Why in the screen shows as "Could not be saved"
No sure if the message of not
![image](https://user-images.githubusercontent.com/23636063/59714734-54a03c80-91e0-11e9-85f0-af068f7ea6d1.png)

**Comment by gnat42** [comment]
Same issue as the clear cache - Also there were messages in the import namespace that needed to be translated (The Please Select... issue for example). However now it should clear the cache and notify me so they won't accidentally be wiped out when you make changes.

**Comment by ClaudiaOrtizD** [comment]
Thanks. I thought I was going crazy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
