### ISSUE TITLE
Pleural fluids is for Pneumonia not Meningitis

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#40]
Pleural fluids is for Pneumonia not Meningitis

**Comment by gnat42** [comment]
I checked and I have pleural fluid in pneumonia not meningitis. Where do you see pleural fluid in Meningitis?

**Comment by ClaudiaOrtizD** [comment]
it is working now

**Comment by gnat42** [comment]
Oh good. So I'll close this then. If all the other variables look like they're in the correct places then I'll start on the next part.
