### ISSUE TITLE
when editing a Case of neumonia appear combo box LCR 

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#41]
![nolcrinneumo](https://user-images.githubusercontent.com/23636063/39717376-9d2246f0-5222-11e8-871b-022b9c47ee95.PNG)

When editing a Case of pneumonia appear combo box LCR. LRC . It should show only in Meningitis

**Comment by ClaudiaOrtizD** [comment]
https://demo.vinuvacasos.org/en/ibd/edit/NIC-NIC-155-18-002078 
it seems continue to be a problem

**Comment by gnat42** [comment]
you're looking at the IBD menu there... The demo is the variable split so look at the meningitis/pneumonia fields not the IBD... that will be deleted once they are complete.
