### ISSUE TITLE
Rotavirus add  question:  Did case have bloody diarrhea?

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#48]
Please add question in Rotavirus , I thought I saw it before .
Did case have bloody diarrhea? Afer the question about the patient presented accute diarrhea
In the clinical tab ==> Variable used  Symp_diarrhea_bloody_YN

Expected Values :
0 = No, 
 1 = Yes,
 99 = Unknown

**Comment by gnat42** [comment]
need to have tac phase 2 set to yes for the site
