### ISSUE TITLE
Data from EPI case does not coincide with the View cases

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#52]
Data from EPI case does not coincide with the View cases, for instance:
[Data from EPI case does not coincide with the View cases.docx](https://github.com/IBVPD/Nuvi/files/2001163/Data.from.EPI.case.does.not.coincide.with.the.View.cases.docx)

In Case 2018-N-PRY-20-9292
1.	Date of birth is different  in the EPI and in the View case (off one day)
2.	Show in the header case ID instead of System id, (for hospital users is better use caseid)
3.	Date of most recent doses of PCV is one day off as well

**Comment by gnat42** [comment]
Fixed. 

The production machine was incorrectly configured. PHP's timezone was set to CET but the server was CEST and so instantiating a date without a time caused there to be a 1 hour difference and brought the date back a day.
