### ISSUE TITLE
Refresh translated Messages and include new labels to translate

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#55]
Please refresh translated labels in live server and include other new labels translate

For instance I don't see the second blood
![2ndblood](https://user-images.githubusercontent.com/23636063/42388691-d6d2757c-8135-11e8-8a1e-4e13ab19e010.PNG)

**Comment by gnat42** [comment]
updated -*EXCEPT* the new variables for the split on the demo site. That will come later.
