### ISSUE TITLE
Users rights configuration question

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#60]
How can you configure users, that have access to create NL data, so they can edit NL data for cases that already entered.
for instance user, martavhv@gmail.com would like to enter serotype data on case 17-n-509277 . Currently just doesn't give you any message when clicking on Save and doesn't save data 

![users not able to edit nl data](https://user-images.githubusercontent.com/23636063/43265734-257a74f6-90d9-11e8-86f4-47cbed1538ca.png)

**Comment by gnat42** [comment]
So if you see the NL fields, you can add/edit. What is likely happening here is there is a required field that is hidden somehow or we aren't detecting it. I would need to know what data they are submitting to be able to reproduce. Then I can fix the underlying error.

**Comment by ClaudiaOrtizD** [comment]
Actually, I cannot edit the serotype of the case id  = 17-n-509277  from Paraguay.
In the picture attached you can enter the data but when you hit on Save .  Nothing happens, no message not saving.
What is the required field that is hidden>
My understanding was that when a user has can create NL is also able to edit data from the site that it has access is this right?

**Comment by gnat42** [comment]
This has been fixed via a work-around
