### ISSUE TITLE
Estatus flag is orange evethough all data is enterend in DEMO site 

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#61]
Status flag is not clear what represent. Eventhough apparently all required data is enter still shows as orange.  Please see example attached.  
![statusorangewithall data filled](https://user-images.githubusercontent.com/23636063/43269431-5ebf5610-90e2-11e8-88e1-d571c07a602b.PNG)

**Comment by gnat42** [comment]
There was a small bug with the Pneumonia code for PAHO cases. Its now fixed. The case needs to be edited to turn green though.

**Comment by ClaudiaOrtizD** [comment]
So all cases will be with wrong status unless are edited again?
Is this going to happen in the live application as well?

**Comment by gnat42** [comment]
For the live version, when we switch, they should be green since we'll be redoing the split from scratch and the status should be picked up properly.

**Comment by gnat42** [comment]
I can re-do the split into the demo to demonstrate.
