### ISSUE TITLE
Remove from LATEX test option Unknown CSF - Meningitis

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#63]
Remove from LATEX test option **Unknown** CSF
[remove unknown from Latex.docx](https://github.com/IBVPD/Nuvi/files/2237058/remove.unknown.from.Latex.docx)

**Comment by ClaudiaOrtizD** [comment]
there is a still an option of unknown

**Comment by ClaudiaOrtizD** [comment]
![latex test still option unknows](https://user-images.githubusercontent.com/23636063/43659940-119d75e4-974d-11e8-98d8-19c841c78516.gif)

**Comment by gnat42** [comment]
fixed
