### ISSUE TITLE
User already exist please help  yolita.narvaez2010@gmail.com 

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#75]
please help not recall what happen with this user ...
I don;t see in the list of users that I could see.
![user-already exists](https://user-images.githubusercontent.com/23636063/46377330-d4ed3480-c687-11e8-93a9-490f8702d1d1.PNG)

**Comment by gnat42** [comment]
She's been 'fixed'. Check the ACL rights she has to make sure they are correct.
