### ISSUE TITLE
Change header for hospital lab  and remove genotyping from hospital lab

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#99]
Change header for hospital lab  and remove genotyping tab  from hospital lab.
Hospital Laboratory does not perform genotyping
![Change header from Hospital lab and remove genotyping ](https://user-images.githubusercontent.com/23636063/58895124-3ce59600-86c1-11e9-9789-de245a533cc6.png)

**Comment by gnat42** [comment]
Ok, this is live. I edited the EN version, you should edit the ES version. If you look at sentinel, ES look for 'Edit Lab For Case %id%' and modify it for whatever works in spanish.
